#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     yawDetector,    sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     accelerometer,  sensorI2CHiTechnicAccel)
#pragma config(Sensor, S4,     irDetector,     sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     leftDrive,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     mainIntake,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     elevator,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     rightDrive,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     goalLifter,    tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    score,                tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-gyro.h";
#include "drivers/hitechnic-accelerometer.h";
#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

float thetaX = 0;
float avgGyroX = 0;
bool finished = false;
int xAxis = 0;
int yAxis = 0;
int zAxis = 0;
float avgXAxis = 0;
float avgYAxis = 0;
float avgZAxis = 0;



void calibrateSensors() {
	while (avgGyroX < 570 || avgGyroX > 630) {
		PlaySound(soundLowBuzz);
	 	for (int i = 0; i < 1000; i ++) {
			avgGyroX += SensorValue[yawDetector];
			wait1Msec(1);
		}
	}
	avgGyroX = avgGyroX/1000;
	PlaySound(soundLowBuzz);
	 for (int i = 0; i < 1000; i ++) {
	 	HTACreadAllAxes(S3, xAxis, yAxis, zAxis);
		avgXAxis += xAxis;
		avgYAxis += yAxis;
	  avgZAxis += zAxis;
		wait1Msec(1);
  }
  avgZAxis = avgZAxis/1000;
}


int getTheta() {
	thetaX = thetaX + ((float)SensorValue[yawDetector]-avgGyroX) * time1[T1] / 1000.0;
	ClearTimer(T1);
	return (int)(thetaX);
}


void turnLeft(int theta) { // PRECONDITION: Theta is positive
	int startAngle = getTheta();
		while(getTheta()%360 > (startAngle-theta)%360) {
			motor[rightDrive] = 100;
			motor[leftDrive] = -100;
	}
}


void turnRight(int theta) {
	int startAngle = getTheta();
	while(getTheta()%360 < (startAngle+theta)%360) {
		motor[rightDrive] = -100;
		motor[leftDrive] = 100;
	}
}


void goForward(int dist) { // PRECONDITION: Dist is positive
	int startLoc = nMotorEncoder[rightDrive];
	while (nMotorEncoder[rightDrive] < startLoc + dist) {
		motor[rightDrive] = 100;
		motor[leftDrive] = 100;
	}
}


void goBackward(int dist) {
	int startLoc = nMotorEncoder[rightDrive];
	while (nMotorEncoder[rightDrive] > startLoc - dist) {
		motor[rightDrive] = -100;
		motor[leftDrive] = -100;
	}
}


bool waitForRamp() {
	bool offRamp = false;
	while (!offRamp) {
	}
	return false;
}


int getAxes() {
	return 0;
}


void initializeRobot()
{
  calibrateSensors();
  servo[servo1] = 0;
}


void autonomous() {
	motor[rightDrive] = -25;
  motor[leftDrive] = -25;
}


task main()
{
  initializeRobot();

  waitForStart(); // Wait for the beginning of autonomous phase.

  autonomous();

  while (true) {
  }
}
