#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     yawDetector,    sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     accelerometer,  sensorI2CHiTechnicAccel)
#pragma config(Sensor, S4,     irDetector,     sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     leftDrive,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     mainIntake,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     elevator,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     rightDrive,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     goalLifter,    tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    score,                tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-gyro.h";
#include "drivers/hitechnic-accelerometer.h";
#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

float thetaX = 0;
float avgGyroX = 0;
bool finished = false;


void calibrateSensors() {
	while (avgGyroX < 570 || avgGyroX > 630) {
		PlaySound(soundLowBuzz);
	 	for (int i = 0; i < 1000; i ++) {
			avgGyroX += SensorValue[yawDetector];
			wait1Msec(1);
		}
	}
	avgGyroX = avgGyroX/1000;
}


float getTheta() {
	thetaX = thetaX + ((float)SensorValue[yawDetector]-avgGyroX) * time1[T1] / 1000.0;
	ClearTimer(T1);
	return (thetaX);
}


void testForOffRamp() {
	bool offRamp = false;
	while (!offRamp) {
	}
}


void initializeRobot()
{
  calibrateSensors();
  servo[score] = 0;
}


void autonomous() {
	motor[rightDrive] = -35;
  motor[leftDrive] = -35;
  while (nMotorEncoder[leftDrive] < 10797) {
  }
  motor[leftDrive] = 0;
  motor[rightDrive] = 0;

  wait1Msec(500);

	motor[rightDrive] = -15;
	motor[leftDrive] = 15;
	while (getTheta() < 26.565) {
	}
	motor[leftDrive] = 0;
  motor[rightDrive] = 0;

  float actualRotation = getTheta();

  wait1Msec(500);

  motor[leftDrive] = 35;
  motor[rightDrive] = 35;
  while (nMotorEncoder[leftDrive] < 10932) {
  }
  motor[leftDrive] = 0;
  motor[rightDrive] = 0;

  motor[rightDrive] = -15;
  motor[leftDrive] = 15;
  while(getTheta() < actualRotation) {
  }
}


task main()
{
  initializeRobot();

  waitForStart(); // Wait for the beginning of autonomous phase.

  autonomous();

  while (true) {
  }
}
