#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     yawDetector,    sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     accelerometer,  sensorI2CHiTechnicAccel)
#pragma config(Sensor, S4,     irDetector,     sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     leftDrive,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     mainIntake,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     elevator,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     rightDrive,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     goalLifter,    tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    score,                tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-gyro.h";
#include "drivers/hitechnic-accelerometer.h";
#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

float yaw = 0;
float avgGyroX = 0;
bool finished = false;


void calibrateSensors() {
	while (avgGyroX < 570 || avgGyroX > 630) {
		PlaySound(soundLowBuzz);
	 	for (int i = 0; i < 1000; i ++) {
			avgGyroX += SensorValue[yawDetector];
			wait1Msec(1);
		}
	}
	avgGyroX = avgGyroX/1000;
}


float getTheta() {
	yaw = yaw + ((float)SensorValue[yawDetector]-avgGyroX) * time1[T1] / 1000.0;
	ClearTimer(T1);
	return (yaw);
}

void forward(int forwardTicks, int speed) {
	nMotorEncoder[rightDrive] = 0;
	nMotorEncoder[leftDrive] = 0;
	nMotorEncoderTarget[rightDrive] = forwardTicks;
	motor[rightDrive] = speed;
	motor[leftDrive] = speed;
	while(nMotorRunState[rightDrive] != runStateIdle) {}
	motor[rightDrive] = 0;
	motor[leftDrive] = 0;
}

void initializeRobot()
{
  //calibrateSensors();
  //servo[score] = 0;
}


void goForward(int dist, int speed) { // PRECONDITION: dist > 0
	nMotorEncoder[leftDrive] = 0;
	nMotorEncoderTarget[leftDrive] = dist*118.8357/1.5; // converts inches to ticks
	motor[leftDrive] = speed;
	motor[rightDrive] = speed;
	while(nMotorRunState[leftDrive] != runStateIdle && nMotorRunState[rightDrive] != runStateIdle) {}
	motor[leftDrive] = 0;
	motor[rightDrive] = 0;
}


void goBackward(int dist, int speed) { // PRECONDITION: dist > 0
	nMotorEncoder[leftDrive] = 0;
	nMotorEncoder[rightDrive] = 0;
	nMotorEncoderTarget[leftDrive] = dist*118.8357/1.5; // converts inches to ticks
	nMotorEncoderTarget[rightDrive] = dist*118.8357/1.5; // converts inches to ticks
	motor[leftDrive] = -speed;
	motor[rightDrive] = -speed;
	while(nMotorRunState[leftDrive] != runStateIdle && nMotorRunState[rightDrive] != runStateIdle) {}
	motor[leftDrive] = 0;
	motor[rightDrive] = 0;
}


void turnRight(int angle) { // PRECONDITION: angle > 0
	yaw = 0;
	while (-getTheta() < angle) {
		motor[leftDrive] = 100;
		motor[rightDrive] = -100;
	}
	motor[leftDrive] = 0;
	motor[rightDrive] = 0;
}


void turnRight(int angle) { // PRECONDITION: angle > 0
	yaw = 0;
	while (getTheta() < angle) {
		motor[leftDrive] = -100;
		motor[rightDrive] = 100;
	}
	motor[leftDrive] = 0;
	motor[rightDrive] = 0;
}


void autonomous() {
	goBackward(120, 50);
}


task main()
{
  initializeRobot();

  waitForStart(); // Wait for the beginning of autonomous phase.

  autonomous();

  while (true) {
  }
}
