#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rightDrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftDrive,     tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


task main()
{
	motor[leftDrive] = 100;
	motor[rightDrive] = 95;
	wait1Msec(3000);
	motor[leftDrive] = -100;
	motor[rightDrive] = -95;
	wait1Msec(3000);
	motor[leftDrive] = 0;
	motor[rightDrive] = 0;
	wait1Msec(100);
	motor[leftDrive] = 100;
	motor[rightDrive] = -95;
	wait1Msec(10000);
	motor[leftDrive] = 0;
	motor[rightDrive] = 0;
}
