#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,      ,             tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// TETRIX nMotorEncoder Example
// The program below demonstrates how to use the nMotorEndocer function
// There are three steps to using the function
//    1. Zero out the encoder using "nMotorEncoder(motorX) = 0"   Lines 16 and 17.
//    2. Place the function into a conditional statement like a while loop.  Line 19
//    3. Turn the motors off. Lines 25 and 26.

task main()
{

  nMotorEncoder[motorD] = 0;

  while (nMotorEncoder[motorD] < 1440) //while the encoder wheel turns one revolution
  {
    motor[motorD] = 30;
    //nxtDisplayCenteredTextLine(5, "%d", nMotorEncoder[motorE]);
    nxtDisplayCenteredTextLine(6, "%d", nMotorEncoder[motorD]);
  }

  motor[motorD] = 0;

  wait1Msec(3000); // wait 3 seconds to see feedback from the debugger screens
                    // open the "NXT Devices" window to see the distance the encoder
                    //spins. The robot will coast a little bit.
}
