
task main()
{



}#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     Bootan,         sensorTouch)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     neverRest,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     tetrixDC,      tmotorTetrix, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int ticks2 = 1120*2.873;
int ticks = 1120*5.873;

task main()
{
	while (true) {
		nMotorEncoder[neverRest] = 0;
		nMotorEncoderTarget[neverRest] = ticks;
		nMotorEncoder[tetrixDC] = 0;
		nMotorEncoderTarget[tetrixDC] = ticks2;
		motor[neverRest] = 100;
		motor[tetrixDC] = 100;
		while(nMotorRunState[neverRest] != runStateIdle && nMotorRunState[tetrixDC] != runStateIdle) {
		}
		if (nMotorRunState[neverRest] == runStateIdle) {
			motor[neverRest] = 0;
			while(nMotorRunState[tetrixDC] != runStateIdle) {}
			motor[tetrixDC] = 0;
		}
	  else {
			motor[tetrixDC] = 0;
			while(nMotorRunState[neverRest] != runStateIdle) {}
			motor[neverRest] = 0;
		}
		while (SensorValue(Bootan) != 1) {
			//nxtDisplayCenteredTextLine(3, "%d", nMotorEncoder[neverRest]);
			//nxtDisplayCenteredTextLine(4, "%d", ticks);
			nxtDisplayCenteredTextLine(5, "%d", nMotorEncoder[neverRest] - ticks);
			nxtDisplayCenteredTextLine(6, "%d", (nMotorEncoder[tetrixDC] - ticks2));
		}
	}
}
