#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     yawDetector,    sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     accelerometer,  sensorI2CHiTechnicAccel)
#pragma config(Sensor, S4,     Bootan,         sensorTouch)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     leftDrive,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     mainIntake,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     elevator,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     rightDrive,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     goalLifter,    tmotorTetrix, PIDControl, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    score,                tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool goingUp = true;

task main()
{
	nMotorEncoder[goalLifter] = 0;
	nMotorEncoderTarget[goalLifter] = 1440;
	motor[goalLifter] = 50;
	while(nMotorRunState[goalLifter] != runStateIdle) {
		nxtDisplayCenteredTextLine(5, "%d", nMotorEncoder[goalLifter]);
	}
	motor[goalLifter] = 0;
	wait10Msec(10);
	while(true) {
		nMotorEncoder[goalLifter] = 0;
		if (goingUp) {
			nMotorEncoderTarget[goalLifter] = 240;
			motor[goalLifter] = 100;
		}
		else {
			nMotorEncoderTarget[goalLifter] = -240;
			motor[goalLifter] = -100;
		}
		while(nMotorRunState[goalLifter] != runStateIdle) {
		}
		motor[goalLifter] = 0;
		while (SensorValue(Bootan) != 1) {
			nxtDisplayCenteredTextLine(5, "%d", nMotorEncoder[goalLifter]);
		}
		goingUp = !goingUp;
	}
}
