#pragma config(Hubs,	S1, HTServo,	none,			none,			none)
#pragma config(Sensor, S1,		 ,							 sensorI2CMuxController)
#pragma config(Servo,	 srvo_S1_C1_1,		evan,									tServoContinuousRotation)
#pragma platform(Tetrix)
//*!!Code automatically generated by 'ROBOTC' configuration wizard							 !!*//

task main() {
	while (true) {
		servo[evan] = 250
	}
}
