#pragma config(Hubs,  S1, HTServo,  none,     none,     none)
#pragma config(Sensor, S2,     Bootan,         sensorTouch)
#pragma config(Servo,  srvo_S1_C1_1,    score,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool down = false;

task main() {
	while(true) {
		if (SensorValue(Bootan) == 1) {
			if (down) {
				servo[score] = 0;
				down = false;
			}
			else {
				servo[score] = 100;
				down = true;
			}
			wait10Msec(50);
		}
	}
}
