#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     yawDetector,    sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     accelerometer,  sensorI2CHiTechnicAccel)
#pragma config(Sensor, S4,     irDetector,     sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     leftDrive,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     mainIntake,    tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     elevator,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     rightDrive,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     goalLifter,    tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

int intakeDir = 0;
bool lastPressed[12];
bool elevatorAtTop = false;
bool elevatorAtBottom = true;
float maxSpeed = 1.0;

void initializeRobot()
{
  return;
}


task main() {
  initializeRobot();

  waitForStart();   // wait for start of tele-op phase

  while (true) { //Literally just controls the Left Drive
		getJoystickSettings(joystick);

		//PlaySound(soundDownwardTones);

		if (abs(joystick.joy1_y1) > 15) {
			motor[leftDrive] = joystick.joy1_y1*maxSpeed;
		}
		else {
			motor[leftDrive] = 0;
		}

	  if (abs(joystick.joy1_y2) > 15) {
			motor[rightDrive] = joystick.joy1_y2*maxSpeed;
		}
		else {
			motor[rightDrive] = 0;
		}

		/*if (joy1Btn(1)) {
			servo[goalLifter] = 30;
		}

		if (joy1Btn(2)) {
			servo[goalLifter] = 0;
		}*/

		/*if (joy1Btn(3)) {
			if (intakeForward) { // Stops intake if going forward
				motor[mainIntake] = 0;
				intakeForward = false;
			}
			else { // Intake goes forward if not in motion
					motor[mainIntake] = 50;
				intakeForward = true;
			}
		}

		if (joy1Btn(4)){ // Stops intake if going backward
			if (intakeBackward) {
				motor[mainIntake] = 0;
				intakeBackward = false;
			}
			else { // Intake goes backward if not in motion
				motor[mainIntake] = -50;
				intakeBackward = true;
			}
		}*/

		if (joy1Btn(3))
			motor[mainIntake] = 80;
	  else if (joy1Btn(1))
	  	motor[mainIntake] = 0;

		/*if (joy1Btn(5)){ //"unscores"
			//\servo[score] = 0;
  	}

		if (joy1Btn(6)){ // Scores
			servo[score] = 20;
		}*/

		if (joy1Btn(7)) {
			motor[elevator] = 50;
		}

		if (joy1Btn(8)) {
			motor[elevator] = -50;
		}

		if (joy1Btn(9) && maxSpeed > 0.0) {
			maxSpeed -= 0.2;
			if (maxSpeed < 0.0) {
				maxSpeed = 0.0;
			}
		}

		if (joy1Btn(10) && maxSpeed < 1.0) {
			maxSpeed += 0.2;
			if (maxSpeed > 1.0) {
				maxSpeed = 1.0;
			}
		}
  }
}
