#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     yawDetector,    sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     accelerometer,  sensorI2CHiTechnicAccel)
#pragma config(Sensor, S4,     irDetector,     sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     leftDrive,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     mainIntake,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     elevator,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     rightDrive,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     goalLifter,    tmotorTetrix, PIDControl, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    autonScore,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    score,                tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


const int raised = 100; // the encoder reading when the goal is raised
const int lowered = 0; // the encoder reading when it is lowered

int intakeDir = 0;
bool lastPressed[12] = {false, false, false, false, false, false, false, false, false, false, false, false};
float maxSpeed = 1.0;


void initializeRobot() {
	nMotorEncoder[goalLifter] = 0;
	nMotorEncoder[elevator] = 0;
}


void raiseGoal() {
	nMotorEncoderTarget[goalLifter] = raised;
	motor[goalLifter] = 30;
}


void lowerGoal() {
	nMotorEncoderTarget[goalLifter] = lowered;
	motor[goalLifter] = -30;
}


void resetMotors() { // stoops motors that need to be stooped
	if (nMotorRunState[goalLifter] == runStateIdle)
		motor[goalLifter] = 0;
}


task main() {
  initializeRobot();

  waitForStart();   // wait for start of tele-op phase

  while (true) { //Literally just controls the Left Drive
		getJoystickSettings(joystick);

		//PlaySound(soundDownwardTones);

		if (abs(joystick.joy1_y1) > 15) {
			motor[leftDrive] = joystick.joy1_y1*maxSpeed;
		}
		else {
			motor[leftDrive] = 0;
		}

	  if (abs(joystick.joy1_y2) > 15) {
			motor[rightDrive] = joystick.joy1_y2*maxSpeed;
		}
		else {
			motor[rightDrive] = 0;
		}

		if (joy1Btn(1) && !lastPressed[1] && nMotorEncoder[goalLifter] < raised) { // if 1 was just pressed and the goal is not raised
			raiseGoal();
		}
		else if (joy1Btn(2) && !lastPressed[2] && nMotorEncoder[goalLifter] > lowered) { // ditto
			lowerGoal();
		}

		if (joy1Btn(3) && !lastPressed[3]) { // if button 3 was just pressed
			if (intakeDir > 0) { // Stops intake if going forward
				motor[mainIntake] = 0;
				intakeDir = 0;
			}
			else { // Intake goes forward if not in motion or backward
				motor[mainIntake] = 80;
				intakeDir = 1;
			}
		}
		else if (joy1Btn(3) && !lastPressed[4]) { // if button 4 was just pressed
			if (intakeDir < 0) { // Stops intake if going backward
				motor[mainIntake] = 0;
				intakeDir = 0;
			}
			else { // Intake goes backward if not in motion or forward
				motor[mainIntake] = -100;
				intakeDir = -1;
			}
		}

		if (joy1Btn(5)){ //"unscores"
			servo[score] = 0;
  	}

		if (joy1Btn(6)){ // Scores
			servo[score] = 100;
		}

		if (joy1Btn(7)) { // if 7 is pressed make elevator go up. (right trigger)
			motor[elevator] = 100;
		}
		else if (joy1Btn(8)) { // if 8 is pressed make elevator go down. (left trigger)
			motor[elevator] = -75;
		}
		else {
			motor[elevator] = 0; // stop the elevator when nothing is pressed.
		}

		if (joy1Btn(9) && !lastPressed[9] && maxSpeed > 0.2) { // if 9 was just pressed and the robot is still moving
			maxSpeed -= 0.2;
		}


		if (joy1Btn(10) && !lastPressed[10] && maxSpeed < 1.0) { // if 10 was just pressed and the robot could go faster
			maxSpeed += 0.2;
		}

		for (int i = 1; i <= 10; i ++)
			lastPressed[i] = joy1Btn(i)>0; // remembers what was pressed

		resetMotors();
  }
}
