#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Motor,  mtr_S1_C1_1,     rightDrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftDrive,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     elevator,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Intake,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_2,    mainScore,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    secondaryScore,       tServoStandard)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


void initializeRobot()
{


  return;
}


task main()
{
  initializeRobot();

  waitForStart();   // wait for start of tele-op phase

  while (true)
  {

  }
}
