#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorTouch)
#pragma config(Motor,  motorA,          goalClamp,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          goalLifter,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     rightDrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftDrive,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     elevator,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     intake,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    mainScore,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    secondaryScore,       tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


void initializeRobot()
{

}


task main()
{
  initializeRobot();

  waitForStart();   // wait for start of tele-op phase

  while (true)
  {
		getJoystickSettings(joystick);

		if (abs(joystick.joy1_y1) > 15)
			motor[leftDrive] = joystick.joy1_y1;
		else
			motor[leftDrive] = 0;

	  if (abs(joystick.joy1_y2) > 15)
			motor[rightDrive] = joystick.joy1_y2;
		else
			motor[rightDrive] = 0;

		if (joy1Btn(8) == 1)
			motor[goalClamp] = 127;
		else if (joy1Btn(7) == 1)
			motor[goalClamp] = -128;
		else
			motor[elevator] = 0;

		if (joy1Btn(6) == 1)
			motor[goalLifter] = 127;
	  else if (joy1Btn(5) == 1)
	  	motor[goalLifter] = -128;
	 	else
	 		motor[intake] = 0;

  }
}
