#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S2,     pitch,          sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     yaw,            sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     direction,      sensorI2CHiTechnicAccel)
#pragma config(Motor,  mtr_S1_C1_1,     rightDrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     leftDrive,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-accelerometer.h"
#include "drivers/hitechnic-gyro.h";
task main() {
	int x = 0;
	int y = 0;
	int z = 0;
	bool offRamp = false;
	bool downRamp = false;
	float thetaY = 0;
	//float thetaX = 0;
	unsigned int t = 0;
	//float avgGyroY = 0;
	//float avgGyroX = 0;
	HTGYROsetCal(pitch, 0);
	motor[rightDrive] = -50;
	motor[leftDrive] = -50;
	HTACreadAllAxes(direction, x, y, z);
	while(!offRamp) {
		t++;
		wait1Msec(100);
		thetaY = thetaY + (HTGYROreadRot(pitch) * time1[T1]) / 1000.0;
		ClearTimer(T1);

		int refY = (int)(thetaY+180)%360 - 180;
		if (refY > 10) {
			downRamp = true;
			PlaySound(soundDownwardTones);
		}
		if (downRamp && refY < 5) {
			offRamp = true;
			PlaySound(soundBeepBeep);
		}
	}
	StopAllTasks();
}
