#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S2,     pitch,          sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     yaw,            sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     direction,      sensorI2CHiTechnicAccel)
#pragma config(Motor,  mtr_S1_C1_1,     rightDrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     leftDrive,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-accelerometer.h"

task main() {
	int x = 0;
	int y = 0;
	int z = 0;
	bool offRamp = false;
	bool downRamp = false;
	motor[rightDrive] = -50;
	motor[leftDrive] = -50;
	wait10Msec(500);
	HTACreadAllAxes(direction, x, y, z);
	while(!offRamp) {
		if (x > 15) {
			downRamp = true;
		}
		if (downRamp && x < 10) {
			offRamp = true;
		}
	}
	StopAllTasks();
}
