#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     pitch,          sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     yaw,            sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     direction,      sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     none,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightDrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     none,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     leftDrive,     tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-accelerometer.h"
#include "drivers/hitechnic-gyro.h";
task main() {
	int x;
	int y;
	int z;
	int waitTime = 0;
	int originalAccel;
	bool offRamp;
	motor[rightDrive] = -50;
	motor[leftDrive] = -50;
	wait10Msec(125);
	HTACreadAllAxes(direction, x, y, z);
	x += 18;
  y -= 4;
  z -= 194;
  originalAccel = z;
	while(!offRamp) {
		motor[rightDrive] = -50;
		motor[leftDrive] = -50;
		HTACreadAllAxes(direction, x, y, z);
		/*if ((abs(originalAccel - z) > 75) || waitTime > 5000) {
			offRamp = true;
		}*/
		wait1Msec(1);
		waitTime++;
	}
	motor[rightDrive] = 0;
	motor[leftDrive] = 0;
}
